### ISSUE TITLE
Getting error [Network error]

### ISSUE THREAD

**Issue by rana-kundu001** [stoplightio/desktop#70]
Hi ,

  I am getting error message saying 'NETWORK ERROR' while running the particular collection(Link is given below). For every scenarios in this collection, I am getting the error. Below is the link of my collection.

https://next.stoplight.io/telstra-media/gmn-service-identity/blob/master/contract.scenarios.yml

Regards,
Rana Kundu

**Comment by ektachawla** [comment]
I also get same error on this particular collection when i run it from my account.

**Comment by marbemac** [comment]
Hi @rana-kundu001 @ektachawla - we've just confirmed that this is fixed in our staging environment. We're deploying an update tomorrow afternoon (US Central Time), after which you should be all set! I'll close this issue out when its live.

**Comment by marbemac** [comment]
Following up here - this should be resolved. Note that there is currently a 30 second time limit on running a collection - does your collection take longer than that? We are updating that time limit to 120 seconds tomorrow.

**Comment by ektachawla** [comment]
yes i still get this error, probably because my collection takes longer
than 30 seconds :(

**Comment by ektachawla** [comment]
hi..i still get Network Error on my collection: https://next.stoplight.io/telstra-media/gmn-service-capacity/blob/master/api.oas2.yml
Can you please help on same.
Thanks

**Comment by pytlesk4** [comment]
@ektachawla are you still getting a network error? I can't reproduce the issue. Prism is having an issue though with parsing your swagger file, because of the hose you have set. We are going to release an update today to the desktop app and prism, that will fix the swagger parsing issue.

**Comment by ektachawla** [comment]
Hi, still getting error :( 
![image](https://user-images.githubusercontent.com/12841322/33073995-a0a101e2-ceea-11e7-8c0a-4ecbca1165a8.png)

**Comment by pytlesk4** [comment]
@ektachawla did some more digging, it looks like when running your scenarios, some of them take a really long time. It is causing the run to time out. Later today we will be releasing an update to help you understand better what is happening, 'Network Error' just isn't very informative. 

Right now, scenario collection run will time out after 2 mins. Your PUT: Reservations is the one that is causing the time out. It takes at least 2 mins to run, if I remove PUT: Reservations and hit Run Collection, I don't get the Network Error anymore. 

Also, Load DB and Setup ids in the before phase of your scenario collection takes about 30 seconds as well, speeding that up will help too.

I will let you know when the update is out. Also, if you download the desktop app, there isn't a 2 minute timeout when running your scenarios.

You can get the latest here: https://github.com/stoplightio/desktop/releases/tag/v3.5.3

**Comment by ektachawla** [comment]
thanks guys! i do not get service error now. Also, like you mentioned, getting a more detailed error message would be helpful. Is time spent in before steps part of the 2 min total? Thanks!

**Comment by pytlesk4** [comment]
Yeah, the before step is part of the 2 min total, the general rule when using our hosted prism service is that any run has a max runtime of two minutes. So all your before, scenarios, and after phases in total need to finish running in 2 mins.

Sometime this week, we will be releasing an update with a detailed error message as well, should be a lot easier to understand what is happening.

Thanks for your patience @ektachawla

**Comment by ektachawla** [comment]
thanks for your help! Is the fix for more descriptive error message out. That would be very helpful.
BR
